### PR TITLE
[ Major Update ] : Major Refector & Reduced Overall Size 

### PR DESCRIPTION
**Pull request by varunsridharan**
@hunzaboy 
First of all thanks for the awesome library. :-)
I have been using this in my project https://github.com/wponion/wponion for a while 
And your recent update which provided me with scss files 
so i worked on it and reduced css output size from combining all common css codes.

| CSS File | Old Size | New Size |
| ------------- | ------------ | ------------ |
| checkboxes.css | 25.5 KB | 10.6 KB |
| checkboxes.min.css | 20.4 KB | 8.72 KB |

### CODE REVIEW

**Comment by varunsridharan** [comment]
@hunzaboy i am holding of my project's release due to this pull request merge. and also looking towards your feedback on this. base on your response i will move on with my work.

**Comment by hunzaboy** [comment]
Hey @varunsridharan, thanks for working on it. I will have a look today and merge the changes.

**Comment by varunsridharan** [comment]
@hunzaboy thanks for your response. awesome take your time. i was bit in a hurry just to know the estimated timeline. so i can manage my other releases.

**Comment by hunzaboy** [comment]
There were minor issue with animation, updated and merged.

**Comment by varunsridharan** [comment]
Awesome :-)

Yea i am trying to get it working. if do then will create a pull request,.

**Pull request merged**
